- src/App.tsx
- src/components/circle/Circle.tsx
- src/components/content/Content.tsx
- src/components/filters-component/FiltersComponent.tsx
- src/components/result/Result.tsx
- src/components/timeline/Timeline.tsx
- src/demoData.ts
- src/interfaces/CustomData.ts
- src/interfaces/GameData.ts
- src/services/gameDataService.ts
- src/utils.ts
- Added GameData.ts for games using https://github.com/peruukki/nhl-recap
- Handmade data.ts should be removed next commit
> Fetch game data

- src/components/filters-component/FiltersComponent.tsx
- src/components/result/Result.tsx
> Test to try merging break

- src/utils.ts
- Fixed so the month is always in english and uppercase
> Fix date format

- src/App.tsx
- src/components/timeline/Timeline.tsx
- src/interfaces/GameData.ts
- src/styles.css
- src/utils/helpers.test.ts
- src/utils/helpers.ts
- Now when filter is applied the unmatched goals get grayed out.
- Fixed tests to match this change
> Change filter action

- src/App.module.css
- src/App.tsx
- src/components/now-visualizing/NowVisualizing.module.css
- Reduced font weigh for 'Now visualizing' text
> Modify styling

- src/App.tsx
- src/components/choose-component/ChooseComponent.module.css
- src/components/choose-component/ChooseComponent.tsx
Created new component for the app
> Add new component ChooseComponent

- index.html
- src/App.module.css
- src/App.tsx
- src/components/navbar/Navbar.module.css
- src/components/navbar/Navbar.tsx
- Added navbar but it's still missing logo and navigation links but I will add them later.
> Add navbar

- src/App.tsx
- src/components/content/Content.tsx
- src/components/goal-circle/GoalCircle.module.css
- src/components/goal-circle/GoalCircle.tsx
- src/components/goal-info-prompt/GoalInfoDialog.module.css
- src/components/goal-info-prompt/GoalInfoDialog.tsx
- src/components/timeline/Timeline.module.css
- src/components/timeline/Timeline.tsx
- src/utils/helpers.test.ts
- src/utils/helpers.ts
- Added new component that opens when hovering on goal event.
> Add new component GoalInfoDialog

- src/components/goal-info-prompt/GoalInfoDialog.tsx
- src/utils/helpers.ts
- Added correct sorting for overtime goals included
- Removed unused function extractWinnerData
> Fix sorting goals

- src/components/goal-circle/GoalCircle.tsx
- Now row expands only when user clicks on the row that has no content under cursor.
> Fix functionality of collapsible row opening

- src/App.tsx
- src/components/content/Content.tsx
- src/components/content/table-body-content/Row.tsx
- src/components/content/table-body-content/TableBodyContent.tsx
- src/components/filters-component/FiltersComponent.tsx
- src/components/game-specific/GameSpecific.tsx
- src/components/goal-circle/GoalCircle.tsx
- src/components/goal-info-prompt/GoalInfoDialog.tsx
- src/components/now-visualizing/NowVisualizing.tsx
- src/components/result/Result.tsx
- src/components/shootout/Shootout.tsx
- src/components/timeline/Timeline.tsx
- src/constants/defaultValues.ts
- src/interfaces/CustomData.ts
- src/utils/utils-tests/filterGoals.test.ts
Refactored App and FiltersComponent. Still needs refactoring
> Code refactoring

- src/App.module.css
Testing if changes are applied
> Testing changes

- src/App.module.css
> Remove red background

- index.html
- src/components/content/table-body-content/Row.tsx
- src/components/content/table-body-content/TableBodyContent.tsx
- src/components/filters-component/FiltersComponent.tsx
- src/components/result/Result.tsx
- src/components/shootout/Shootout.tsx
- src/utils/helpers.ts
- Disabled filter options that are not implemented yet to the app
- Color of selected teams name appears now red in the match table
- Used !important to apply font Roboto Mono everywhere in index.html
- Added indicator if match had shootout. If selected team won -> red if not -> black
> Add requested fixes

- src/components/shootout/Shootout.tsx
- Styles in shootout circle looks better now when hovering or selected.
> Fix shootout circle styles

- src/components/content/table-body-content/TableBodyContent.tsx
- src/components/game-specific/GameSpecific.tsx
- src/components/shootout/Shootout.tsx
> Add shootout info

- src/components/goal-info-prompt/GoalInfoDialog.module.css
> More changes to goal info dialog

- src/components/choose-component/ChooseComponent.module.css
- src/components/choose-component/ChooseComponent.tsx
> Choose component changes

- src/components/choose-component/ChooseComponent.module.css
- src/components/choose-component/ChooseComponent.tsx
> More changes to choose component

- src/components/choose-component/ChooseComponent.module.css
- src/components/choose-component/ChooseComponent.tsx
> Header changes
